### PR TITLE
Null Pointer Exception in SwingStrategiesUI.java

### PR DESCRIPTION
**Pull request by chirazAmara**
in the method   private void setWidgetListeners(StrategyUI strategyUI), widget.getParameter() return null when widget is instance of SwingLabelWidget

### CODE REVIEW

**Comment by johnnyshields** [comment]
Hmm... you didn't raise this pull request correctly.

Anyway, it looks like @rob3rtb already fixed your issue. I've merged his fix to master, can you please try it?

**Comment by chirazAmara** [comment]
hi,
seems to be fine, so when this is released please?

2015-01-30 17:13 GMT+01:00 Johnny Shields <notifications@github.com>:

**Comment by johnnyshields** [comment]
I've just tagged 3.0.3

**Comment by chirazAmara** [comment]
yes - thankyou! please what for the jar file? I need to download it from
your project

2015-01-30 18:36 GMT+01:00 Johnny Shields <notifications@github.com>:

**Comment by johnnyshields** [comment]
We're not currently providing a jar as far as I'm aware, can you compile it yourself from the source please?

**Comment by chirazAmara** [comment]
Please I need it urgently! I'm trying to compile, I have some errors.....
Could you check please? Just compile it

**Comment by johnnyshields** [comment]
I haven't used this library in a long time. @rob3rtb @croydondias can one of you guys help with a build? We should put it in a `/dist/` dir.

**Comment by chirazAmara** [comment]
any updates please

Best Regards,
Chiraz AMARA

2015-01-30 19:08 GMT+01:00 Johnny Shields <notifications@github.com>:

**Comment by johnnyshields** [comment]
@chirazAmara if you want this urgently you're going to have to build it yourself.

**Comment by rob3rtb** [comment]
@chirazAmara @johnnyshields I just attached 3.0.3 build to the release

**Comment by chirazAmara** [comment]
tested and it's working fine, no exception is displayed

2015-02-02 10:13 GMT+01:00 Robert Brouard <notifications@github.com>:

**Comment by johnnyshields** [comment]
@rob3rtb thank you very much!

**Pull request closed without merging**
